### PR TITLE
Front End Design - related issues: #9, #10, #18, #25, #27 

### PR DESCRIPTION
**Pull request by superdina68**
Carla committed Login.html including departments & category pages
Dina recommitted with certain typos fixed in login.html.  
Issues 9, 10 and 18 are in progress

### CODE REVIEW

**Review by Tharsipa — APPROVED** [review]
The corrections made looks good.

**Review by Ahed752 — APPROVED** [review]

**Comment by superdina68** [comment]
Review once again please- header added.  also style.css needs 2 errors corrected on line 122 @CarlaShawi.  Not really certain on what to do.

**Comment by superdina68** [comment]
New commits set- header and footer added everywhere.  Header missing from the product description pages (it gets distorted need to verify with team).  Missing Index Page.  Created a "Page Not Found" as well.

**Comment by CarlaShawi** [comment]
Regarding the header and footer that were added everywhere I think we should fix it for the category pages since the footer and the actual page content have no space in between. (Just style issue to be fixed)

**Comment by superdina68** [comment]
this branch was merged in to backend for .php creation- which was then merged into the master branch

**Comment by CarlaShawi** [comment]
Should be good everything was fixed and done

**Review by CarlaShawi — APPROVED** [review]

**Pull request closed without merging**
