### PR TITLE
Backend ( #10, #12, #13, #15, #16, #20, #29)

### PR DESCRIPTION
**Pull request by raccoonrick**
Added necessary files for the related issues
To be done: orderReview and cancel order (BACK END)

### CODE REVIEW

**Review by superdina68 — APPROVED** [review]
Waiting on the additional files - the rest looks good!

**Review by CarlaShawi — APPROVED** [review]
It's perfect and functional. 
Waiting for others to upload the missing part of the backend.

**Review by Tharsipa — APPROVED** [review]
All changes made are correct.

**Review by J-P-engdev — APPROVED** [review]
Everything looks fine when shopping on the website!

**Pull request merged**
